/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    events: Event;
    categories: Category;
    registrations: Registration;
    subscribers: Subscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    registrations: RegistrationsSelect<false> | RegistrationsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    'homepage-hero': HomepageHero;
    'homepage-pillars': HomepagePillar;
    'homepage-speckit': HomepageSpeckit;
    'homepage-contact': HomepageContact;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'homepage-hero': HomepageHeroSelect<false> | HomepageHeroSelect<true>;
    'homepage-pillars': HomepagePillarsSelect<false> | HomepagePillarsSelect<true>;
    'homepage-speckit': HomepageSpeckitSelect<false> | HomepageSpeckitSelect<true>;
    'homepage-contact': HomepageContactSelect<false> | HomepageContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'premium' | 'registered') | null;
  stripeCustomerId?: string | null;
  subscriptionStatus?: ('active' | 'cancelled' | 'none') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  categories?: (number | Category)[] | null;
  author?: (number | null) | User;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  premium?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  date: string;
  endDate?: string | null;
  location?: string | null;
  /**
   * Zoom/Teams link (visible after registration)
   */
  virtualLink?: string | null;
  capacity?: number | null;
  /**
   * 0 = free event
   */
  price?: number | null;
  stripePriceId?: string | null;
  registrationDeadline?: string | null;
  status?: ('upcoming' | 'past' | 'cancelled') | null;
  /**
   * Post-event recording (can be gated as premium)
   */
  recording?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations".
 */
export interface Registration {
  id: number;
  user: number | User;
  event: number | Event;
  registeredAt?: string | null;
  paymentStatus?: ('paid' | 'free' | 'pending') | null;
  stripePaymentId?: string | null;
  attended?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  source?: ('newsletter' | 'event' | 'premium') | null;
  resendSynced?: boolean | null;
  hubspotSynced?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'registrations';
        value: number | Registration;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  stripeCustomerId?: T;
  subscriptionStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  featuredImage?: T;
  categories?: T;
  author?: T;
  publishedAt?: T;
  status?: T;
  premium?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  featuredImage?: T;
  date?: T;
  endDate?: T;
  location?: T;
  virtualLink?: T;
  capacity?: T;
  price?: T;
  stripePriceId?: T;
  registrationDeadline?: T;
  status?: T;
  recording?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "registrations_select".
 */
export interface RegistrationsSelect<T extends boolean = true> {
  user?: T;
  event?: T;
  registeredAt?: T;
  paymentStatus?: T;
  stripePaymentId?: T;
  attended?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  resendSynced?: T;
  hubspotSynced?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  contactEmail?: string | null;
  socialLinks?: {
    github?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  navItems?:
    | {
        label: string;
        href: string;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-hero".
 */
export interface HomepageHero {
  id: number;
  /**
   * Small badge text above the headline (e.g., "Engineering Enablement")
   */
  badgeLabel: string;
  /**
   * Main hero headline — the first thing visitors read
   */
  headline: string;
  /**
   * Supporting paragraph below the headline — explain what AHA does and why it matters
   */
  subheadline: string;
  /**
   * Primary action button (left/top)
   */
  primaryCta: {
    /**
     * Button label
     */
    text: string;
    /**
     * Button destination URL (e.g., "/services")
     */
    link: string;
  };
  /**
   * Secondary action button (right/bottom)
   */
  secondaryCta: {
    /**
     * Button label
     */
    text: string;
    /**
     * Button destination URL (e.g., "/contact")
     */
    link: string;
  };
  /**
   * Optional pull quote displayed alongside the hero (leave empty to hide)
   */
  quote?: {
    /**
     * Quote text (optional — leave empty to hide the quote)
     */
    text?: string | null;
    /**
     * Quote attribution (required if quote text is provided)
     */
    attribution?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-pillars".
 */
export interface HomepagePillar {
  id: number;
  /**
   * Main heading for the pillars section
   */
  sectionHeading: string;
  /**
   * Description paragraph below the section heading
   */
  sectionSubheading: string;
  /**
   * Small label text in the top-right corner of the section
   */
  sectionLabel: string;
  /**
   * Service pillars — each represents a key offering. Drag to reorder.
   */
  pillars: {
    /**
     * Material Symbols icon name (e.g., "hub", "rocket_launch", "strategy")
     */
    icon: string;
    /**
     * Pillar heading (e.g., "SpecKit Platform")
     */
    title: string;
    /**
     * Pillar description paragraph
     */
    description: string;
    /**
     * Capability tags listed under the description
     */
    capabilities: {
      /**
       * Capability tag text (e.g., "Spec-Driven Development")
       */
      label: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-speckit".
 */
export interface HomepageSpeckit {
  id: number;
  /**
   * Small label text above the heading
   */
  sectionLabel: string;
  /**
   * Main section heading
   */
  heading: string;
  /**
   * Main description paragraph explaining SpecKit's triple nature
   */
  description: string;
  /**
   * Qualitative proof point text below the description
   */
  proofPoint: string;
  /**
   * Feature cards showcasing SpecKit facets (Platform, Framework, Methodology)
   */
  featureCards: {
    /**
     * Material Symbols icon name (e.g., "devices", "engineering", "school")
     */
    icon: string;
    /**
     * Card heading
     */
    title: string;
    /**
     * Card description
     */
    description: string;
    id?: string | null;
  }[];
  /**
   * Heading for the integration highlight card at the bottom
   */
  integrationTitle: string;
  /**
   * Description for the integration highlight card
   */
  integrationDescription: string;
  /**
   * Call-to-action link in the integration card
   */
  cta: {
    /**
     * CTA link text
     */
    text: string;
    /**
     * CTA destination URL
     */
    link: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-contact".
 */
export interface HomepageContact {
  id: number;
  /**
   * Main heading for the contact section
   */
  heading: string;
  /**
   * Supporting paragraph below the heading
   */
  subheadline: string;
  /**
   * Contact info entries shown beside the form (email, phone, address, etc.)
   */
  contactEntries?:
    | {
        /**
         * Material Symbols icon name (e.g., "mail", "phone", "location_on")
         */
        icon: string;
        /**
         * Entry label (e.g., "Email")
         */
        label: string;
        /**
         * Entry value (e.g., "roger@ahasw.com")
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Dropdown options for the "Primary Challenge" field in the contact form
   */
  challengeOptions: {
    /**
     * Challenge option text shown in the dropdown (e.g., "AI Readiness Assessment")
     */
    label: string;
    id?: string | null;
  }[];
  /**
   * Text on the form submit button
   */
  submitButtonText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  contactEmail?: T;
  socialLinks?:
    | T
    | {
        github?: T;
        linkedin?: T;
        twitter?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-hero_select".
 */
export interface HomepageHeroSelect<T extends boolean = true> {
  badgeLabel?: T;
  headline?: T;
  subheadline?: T;
  primaryCta?:
    | T
    | {
        text?: T;
        link?: T;
      };
  secondaryCta?:
    | T
    | {
        text?: T;
        link?: T;
      };
  quote?:
    | T
    | {
        text?: T;
        attribution?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-pillars_select".
 */
export interface HomepagePillarsSelect<T extends boolean = true> {
  sectionHeading?: T;
  sectionSubheading?: T;
  sectionLabel?: T;
  pillars?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        capabilities?:
          | T
          | {
              label?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-speckit_select".
 */
export interface HomepageSpeckitSelect<T extends boolean = true> {
  sectionLabel?: T;
  heading?: T;
  description?: T;
  proofPoint?: T;
  featureCards?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  integrationTitle?: T;
  integrationDescription?: T;
  cta?:
    | T
    | {
        text?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-contact_select".
 */
export interface HomepageContactSelect<T extends boolean = true> {
  heading?: T;
  subheadline?: T;
  contactEntries?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  challengeOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  submitButtonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}